Description: |
    AWS Cloudformation example to deploy a high availability web app.
Parameters:
    CIDR-VPC:
        Description: CIDR Network for VPC
        Type: String
        Default: 10.1.0.0/16
        AllowedPattern: (\d{1,3}){3}\.\d{1,3}/\d{2}
    Project-Name:
        Description: Project Name
        Type: String
        Default: IAC-Udacity
Resources:
    WEB-VPC:
        Type: AWS::EC2::VPC
        Properties: 
          CidrBlock: !Ref CIDR-VPC
          Tags: 
            - Key: Project
              Value: !Ref Project-Name